/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BotsBotIdRouteImport } from './routes/bots.$botId'
import { Route as ApiStudioChatRouteImport } from './routes/api/studio/chat'
import { Route as ApiPublicBotsBotIdWebhookRouteImport } from './routes/api/public/bots/$botId/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsBotIdRoute = BotsBotIdRouteImport.update({
  id: '/bots/$botId',
  path: '/bots/$botId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudioChatRoute = ApiStudioChatRouteImport.update({
  id: '/api/studio/chat',
  path: '/api/studio/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotsBotIdWebhookRoute =
  ApiPublicBotsBotIdWebhookRouteImport.update({
    id: '/api/public/bots/$botId/webhook',
    path: '/api/public/bots/$botId/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/api/studio/chat': typeof ApiStudioChatRoute
  '/api/public/bots/$botId/webhook': typeof ApiPublicBotsBotIdWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/api/studio/chat': typeof ApiStudioChatRoute
  '/api/public/bots/$botId/webhook': typeof ApiPublicBotsBotIdWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/api/studio/chat': typeof ApiStudioChatRoute
  '/api/public/bots/$botId/webhook': typeof ApiPublicBotsBotIdWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bots/$botId'
    | '/api/studio/chat'
    | '/api/public/bots/$botId/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bots/$botId'
    | '/api/studio/chat'
    | '/api/public/bots/$botId/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bots/$botId'
    | '/api/studio/chat'
    | '/api/public/bots/$botId/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BotsBotIdRoute: typeof BotsBotIdRoute
  ApiStudioChatRoute: typeof ApiStudioChatRoute
  ApiPublicBotsBotIdWebhookRoute: typeof ApiPublicBotsBotIdWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/$botId': {
      id: '/bots/$botId'
      path: '/bots/$botId'
      fullPath: '/bots/$botId'
      preLoaderRoute: typeof BotsBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/studio/chat': {
      id: '/api/studio/chat'
      path: '/api/studio/chat'
      fullPath: '/api/studio/chat'
      preLoaderRoute: typeof ApiStudioChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bots/$botId/webhook': {
      id: '/api/public/bots/$botId/webhook'
      path: '/api/public/bots/$botId/webhook'
      fullPath: '/api/public/bots/$botId/webhook'
      preLoaderRoute: typeof ApiPublicBotsBotIdWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BotsBotIdRoute: BotsBotIdRoute,
  ApiStudioChatRoute: ApiStudioChatRoute,
  ApiPublicBotsBotIdWebhookRoute: ApiPublicBotsBotIdWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
